name: "base plan 2"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets: 
      my_github_secret:
        required: true

jobs:
  # --- PLAN JOB ---
  # Runs automatically on every push to check for syntax and logic
  plan:
    name: "Tofu Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./snowflaketest
    env:
      TF_VAR_my_github_secret: ${{ secrets.my_github_secret }}
      TF_VAR_environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.11.5

      - name: Tofu Init
        run: tofu init

      - name: Tofu Plan
        run: |
          mkdir -p ${{ github.workspace }}/plans
          echo "----- TOFU PLAN ----- Cleaning up the output by hiding (known after apply) to reduce noise "
          tofu plan -out=${{ github.workspace }}/plans/snowflake-${{ inputs.environment }} | grep -v "known after apply"

      - name: Tofu Plan again
        run: |
          echo "----- TOFU PLAN -----"
          tofu plan -out=${{ github.workspace }}/plans/just_test

      - name: Upload Tofu Plan
        uses: actions/upload-artifact@v4
        with:
          name: 'TF-Plan-${{ inputs.environment }}'
          path: ${{ github.workspace }}/plans/snowflake-${{ inputs.environment }}
          retention-days: 1