name: "base apply 2"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets: 
      my_github_secret:
        required: true

jobs:
  # --- apply JOB ---
  # Runs automatically on every push to check for syntax and logic
  apply:
    name: "Tofu apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./snowflaketest
    environment: 
      name: ${{ inputs.environment }}
    env:
      TF_VAR_my_github_secret: ${{ secrets.my_github_secret }}
      TF_VAR_environment: ${{ inputs.environment }}
      PLAN_FILE : ${{ github.workspace }}/plans/snowflake-${{ inputs.environment }}.tfplan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.11.5


      - name: Download Plan
        id: download-plan
        uses: actions/download-artifact@v4
        with:
          name: 'TF-Plan-${{ inputs.environment }}'
          path: ${{ github.workspace }}/plans/


      - name: Tofu Init
        run: tofu init

      - name: Tofu apply
        run: |
          echo "----- TOFU apply -----"
          tofu apply ${{ env.PLAN_FILE }}
