name: "base apply 2"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets: 
      my_github_secret:
        required: true

jobs:
  
  apply:
    name: "Tofu Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./snowflake
    
    # IMPORTANT: This links to a GitHub Environment with protection rules
    environment: 
      name: ${{ inputs.environment }}
      url: https://github.com
    env:
      TF_VAR_my_github_secret: ${{ secrets.my_github_secret }}
      TF_VAR_environment: ${{ inputs.environment }}


    steps:
      - name: Tofu Apply
        run: echo 'would apply' #tofu apply -auto-approve
