name: "CD-Opentofu"

on:
  pull_request:
    types:
      - [closed]
    branches:
      - main
  workflow_dispatch: # Allows manual trigger for testing

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  call-CD-Opentofu-plan-prod:
    if: github.event.pull_request.merged == true
    uses: ./.github/workflows/CD-Opentofu-plan.yml
    with:
      environment: "PROD"

  call-CD-Opentofu-apply-prod:
    if: github.event.pull_request.merged == true
    needs: call-CD-Opentofu-plan-prod
    uses: ./.github/workflows/CD-Opentofu-apply.yml
    with:
      environment: "PROD"
