name: "CD-Opentofu-apply"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string


jobs:

  apply:
    name: "Tofu Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./azure

    # IMPORTANT: This links to a GitHub Environment with protection rules
    environment:
      name: ${{ inputs.environment }}
      url: https://github.com
    env:
      PLAN_FILE: ${{ github.workspace }}/plans/azure-${{ inputs.environment }}.tfplan
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: "true"


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure OIDC Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.11.5

      - name: Download Plan
        id: download-plan
        uses: actions/download-artifact@v4
        with:
          name: 'TF-Plan-${{ inputs.environment }}'
          path: ${{ github.workspace }}/plans/

      - name: Tofu Init
        run: tofu init

      - name: Tofu Apply
        run: |
          echo "----- TOFU APPLY -----"
          tofu apply -input=false ${{ env.PLAN_FILE }}