name: "CD-Opentofu-CICD"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - 'snowflake/**'

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  call-CD-Opentofu-plan-cicd:
    uses: ./.github/workflows/CD-Opentofu-plan.yml
    with:
      environment: "CICD"

  call-CD-Opentofu-apply-cicd:
    needs: call-CD-Opentofu-plan-cicd
    if: needs.call-CD-Opentofu-plan-cicd.outputs.has_changes == 'true'
    uses: ./.github/workflows/CD-Opentofu-apply.yml
    with:
      environment: "CICD"