name: "CD-Opentofu-plan"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    outputs:
      has_changes:
        description: "Whether the plan contains changes (exit code 2). False means no-op."
        value: ${{ jobs.plan.outputs.has_changes }}

permissions:
  contents: read
  id-token: write


jobs:
  plan:
    name: "Tofu Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./snowflake
    outputs:
      has_changes: ${{ steps.plan.outputs.has_changes }}
    env:
      PLAN_FILE: ${{ github.workspace }}/plans/snowflake-${{ inputs.environment }}.tfplan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.11.5
          tofu_wrapper: false

      - name: Tofu Init
        run: tofu init

      - name: Tofu Plan
        id: plan
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/plans
          echo "----- TOFU PLAN ----- Hiding (known after apply) to reduce noise"
          set +e

          tofu plan -detailed-exitcode -input=false -out=${{ env.PLAN_FILE }} | grep -v "known after apply"
          
          EXIT_CODE=${PIPESTATUS[0]}
          echo  "exit code: $EXIT_CODE"

          if [ "$EXIT_CODE" -eq 0 ]; then
            echo "Plan complete — no changes."
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          elif [ "$EXIT_CODE" -eq 2 ]; then
            echo "Plan complete — changes detected."
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "Tofu plan failed with exit code $EXIT_CODE"
            exit $EXIT_CODE
          fi

      - name: Upload Tofu Plan
        if: steps.plan.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: 'TF-Plan-${{ inputs.environment }}'
          path: ${{ env.PLAN_FILE }}
          retention-days: 1
