name: "CD-Opentofu-plan"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string


jobs:
  plan:
    name: "Tofu Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./azure
    env:
      PLAN_FILE: ${{ github.workspace }}/plans/azure-${{ inputs.environment }}.tfplan
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: "true"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure OIDC Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.11.5

      - name: Tofu Init
        run: tofu init

      - name: Tofu Plan
        run: |
          mkdir -p ${{ github.workspace }}/plans
          echo "----- TOFU PLAN ----- Cleaning up the output by hiding (known after apply) to reduce noise "
          set -o pipefail
          tofu plan -input=false -out=${{ env.PLAN_FILE }} | grep -v "known after apply"

      - name: Upload Tofu Plan
        uses: actions/upload-artifact@v4
        with:
          name: 'TF-Plan-${{ inputs.environment }}'
          path: ${{ env.PLAN_FILE }}
          retention-days: 1