name: "CD"

on:
  push:
    branches:
      - main
      - 'feature/*'
  workflow_dispatch: # Allows manual trigger for testing

permissions:
  contents: read
  id-token: write

jobs:

  call-base-dev-plan2:
    concurrency:
      group: dev-group-plan2
      cancel-in-progress: true
    uses: ./.github/workflows/base-plan2.yml
    secrets:
      my_github_secret: ${{ secrets.my_github_secret_dev }}
    with:
      environment: DEV
