name: Echo Done

on:
  schedule:
    - cron: "30 13 * * *"
      timezone: "America/Chicago"
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Done
        run: echo done
