name: "OpenTofu SDLC"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      my_github_secret:
        required: true

jobs:
  # --- PLAN JOB ---
  # Runs automatically on every push to check for syntax and logic
  plan:
    name: "Tofu Plan"
    runs-on: ubuntu-latest
    env:
      TF_VAR_my_github_secret: ${{ secrets.my_github_secret }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: 1.11.5

      - name: Tofu Init
        run: tofu init

      - name: Tofu Plan
        run: tofu plan -var="environment=${{ inputs.environment }}"

  # --- APPLY JOB ---
  # Only runs after Plan succeeds and requires manual approval
  apply:
    name: "Tofu Apply"
    needs: plan
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only allow apply from main branch
    
    # IMPORTANT: This links to a GitHub Environment with protection rules
    environment: PROD 
    env:
      TF_VAR_my_github_secret: ${{ secrets.my_github_secret }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Tofu Init
        run: tofu init

      - name: Tofu Apply
        run: echo "This would apply changes for environment ${{ inputs.environment }}"

      - name: Loop secret safely
        run: |
          for (( i=0; i<${#TF_VAR_my_github_secret}; i++ )); do
            char="${TF_VAR_my_github_secret:$i:1}"
            # usar el carácter sin imprimirlo
            echo "Procesando carácter $char"
          done