name: "OpenTofu SDLC - Multiple Environments"

on:
  push:
    branches:
      - main
      - 'feature/*'
  workflow_dispatch: # Allows manual trigger for testing

jobs:

  call-tofu-base-qa:
    concurrency:
      group: qa-group
      cancel-in-progress: true
    uses: ./.github/workflows/tofu-base.yml
    with:
      environment: QA
    secrets: 
      my_github_secret: ${{ secrets.my_github_secret }}

  call-tofu-base-dev:
    concurrency:
      group: dev-group
      cancel-in-progress: true
    uses: ./.github/workflows/tofu-base.yml
    with:
      environment: DEV
    secrets: 
      my_github_secret: ${{ secrets.my_github_secret }}