name: "OpenTofu SDLC"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets: 
      my_github_secret:
        required: true

jobs:
  
  apply:
    name: "Tofu Apply"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./snowflake
    if: github.ref == 'refs/heads/main' # Only allow apply from main branch
    
    # IMPORTANT: This links to a GitHub Environment with protection rules
    environment: 
      name: Apply
    env:
      TF_VAR_my_github_secret: ${{ secrets.my_github_secret }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Tofu Init
        run: tofu init

      - name: Tofu Apply
        run: echo "This would apply changes for environment ${{ inputs.environment }}"

      - name: Loop secret safely
        run: |
          for (( i=0; i<${#TF_VAR_my_github_secret}; i++ )); do
            char="${TF_VAR_my_github_secret:$i:1}"
            # usar el carácter sin imprimirlo
            echo "Procesando carácter $char"
          done